apiVersion: v1
kind: Secret
metadata:
  name: azdevops-agent-secret
  namespace: azdevops-agent
type: Opaque
stringData:
#  AZP_URL: "https://dev.azure.com/azdemofeb2026"
#  AZP_TOKEN: "6kGjtq95HjMfXsJag8zlmervojk1Td1laW4A4dkg0F5RVCeG4jGuJQQJ99CBACAAAAAAAAAAAAASAZDO4L5y"
#  AZP_POOL: "Default"
  VSTS_ACCOUNT: "azdemofeb2026"
  VSTS_TOKEN: "6kGjtq95HjMfXsJag8zlmervojk1Td1laW4A4dkg0F5RVCeG4jGuJQQJ99CBACAAAAAAAAAAAAASAZDO4L5y"
  VSTS_POOL: "Default"
